version: '3.8'

services:
  # MongoDB Database Service
  mongo:
    image: mongo:7.0
    container_name: task-manager-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskmanager
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-manager-network

  # NestJS Application Service  
  app:
    build: .
    container_name: task-manager-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      # Mount source code for development hot reload
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - task-manager-network

# Define volumes for data persistence
volumes:
  mongodb_data:
    driver: local

# Define networks for container communication
networks:
  task-manager-network:
    driver: bridge